CREATE TABLE ACCOUNT (
	ACCOUNT_ID       BIGINT    AUTO_INCREMENT PRIMARY KEY,
	DOCUMENT_NUMBER  TEXT NOT NULL
);

CREATE TABLE OPERATION_TYPE (
	OPERATION_TYPE_ID  BIGINT  PRIMARY KEY,
	DESCRIPTION        TEXT NOT NULL,
	TYPE               TEXT NOT NULL
);

CREATE TABLE TRANSACTION (
	TRANSACTION_ID       BIGINT    AUTO_INCREMENT PRIMARY KEY,
	FK_ACCOUNT_ID  BIGINT NOT NULL,
	FK_OPERATION_TYPE_ID  BIGINT  NOT NULL,
	AMOUNT  DOUBLE  NOT NULL,
	EVENT_DATE DATETIME NOT NULL,
    FOREIGN KEY (FK_ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID),
    FOREIGN KEY (FK_OPERATION_TYPE_ID) REFERENCES OPERATION_TYPE(OPERATION_TYPE_ID)
);

insert into OPERATION_TYPE (OPERATION_TYPE_ID, DESCRIPTION, TYPE) values (1, 'COMPRA A VISTA', 'NEGATIVE');
insert into OPERATION_TYPE (OPERATION_TYPE_ID, DESCRIPTION, TYPE) values (2, 'COMPRA PARCELADA', 'NEGATIVE' );
insert into OPERATION_TYPE (OPERATION_TYPE_ID, DESCRIPTION, TYPE) values (3, 'SAQUE', 'NEGATIVE');
insert into OPERATION_TYPE (OPERATION_TYPE_ID, DESCRIPTION, TYPE) values (4, 'PAGAMENTO', 'POSITIVE');
